version: '3.9'

services:
  sametime-widget-proxy:
    image: "sametime-widget-proxy:latest"
    container_name: sametime-widget-proxy
    restart: always
    user: 1001:1001
    build: .
    environment:
      DEBUG: "express:*"
      PROXY_DEBUG: "info"
      SAMETIME_HOST: "dosam.collab.cloud"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  